<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>Assets\goatshot-icon.ico</ApplicationIcon>
    <AssemblyName>GoatShot</AssemblyName>
    <RootNamespace>GoatShot.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\goatshot-icon.ico" />
    <Resource Include="Assets\goatshot-logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AnimatedGif" Version="1.0.5" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.14" />
  </ItemGroup>

</Project>
