#ifndef AppVersion
#define AppVersion "0.3.0"
#endif

#ifndef PublishDir
#define PublishDir "..\artifacts\publish\Receipts-win-x64"
#endif

#ifndef OutputDir
#define OutputDir "..\artifacts\dist"
#endif

[Setup]
AppId={{4E86AB11-3D28-4D42-BD31-05C48CF751D6}
AppName=Receipts
AppVersion={#AppVersion}
AppPublisher=Receipts
AppPublisherURL=https://github.com/spurnout/witness
DefaultDirName={localappdata}\Programs\Receipts
DefaultGroupName=Receipts
DisableProgramGroupPage=yes
OutputDir={#OutputDir}
OutputBaseFilename=Receipts-{#AppVersion}-win-x64
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\Receipts.exe
SetupLogging=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Shortcuts"; Flags: unchecked
Name: "startup"; Description: "Start Receipts when I sign in"; GroupDescription: "Startup"; Flags: unchecked

[Files]
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Receipts"; Filename: "{app}\Receipts.exe"
; autodesktop resolves to the user desktop for per-user (lowest-privilege) installs
; and the common desktop when elevated; commondesktop is not writable without elevation.
Name: "{autodesktop}\Receipts"; Filename: "{app}\Receipts.exe"; Tasks: desktopicon

[Registry]
; Must stay byte-for-byte identical to StartupRegistrationService.BuildStartupCommand, which writes
; "<exe>" --background. Without the argument the app starts with a visible window instead of going to
; the tray, and StartupRegistrationService.GetState reports the command as stale on every upgrade.
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "Receipts"; ValueData: """{app}\Receipts.exe"" --background"; Flags: uninsdeletevalue; Tasks: startup
; The app registers browser native-messaging hosts at runtime; dontcreatekey +
; uninsdeletekey schedules their removal at uninstall without creating them here,
; so browsers don't keep a host pointing at the deleted Receipts.exe. The legacy
; alias remains registered by the app during the compatibility window.
Root: HKCU; Subkey: "Software\Google\Chrome\NativeMessagingHosts\com.receipts.bridge"; Flags: dontcreatekey uninsdeletekey
Root: HKCU; Subkey: "Software\Microsoft\Edge\NativeMessagingHosts\com.receipts.bridge"; Flags: dontcreatekey uninsdeletekey
Root: HKCU; Subkey: "Software\Google\Chrome\NativeMessagingHosts\com.goatshot.bridge"; Flags: dontcreatekey uninsdeletekey
Root: HKCU; Subkey: "Software\Microsoft\Edge\NativeMessagingHosts\com.goatshot.bridge"; Flags: dontcreatekey uninsdeletekey

[UninstallDelete]
; Native-messaging manifests generated by the app; remove them so browsers stop
; resolving a host that no longer exists. User capture data is left untouched.
Type: filesandordirs; Name: "{localappdata}\Receipts\browser-bridge\native-host"
Type: filesandordirs; Name: "{localappdata}\GoatShot\browser-bridge\native-host"
Type: files; Name: "{userappdata}\Mozilla\NativeMessagingHosts\com.receipts.bridge.json"
Type: files; Name: "{userappdata}\Mozilla\NativeMessagingHosts\com.goatshot.bridge.json"

[Run]
Filename: "{app}\Receipts.exe"; Description: "Launch Receipts"; Flags: nowait postinstall skipifsilent

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    { Keep the shared AppId for in-place upgrades, then remove obsolete launch
      entries only after the Receipts files have installed successfully. }
    RegDeleteValue(HKCU, 'Software\Microsoft\Windows\CurrentVersion\Run', 'GoatShot');
    DeleteFile(ExpandConstant('{userdesktop}\GoatShot.lnk'));
    DeleteFile(ExpandConstant('{userprograms}\GoatShot\GoatShot.lnk'));
    RemoveDir(ExpandConstant('{userprograms}\GoatShot'));
  end;
end;
